include: package:lints/recommended.yaml

analyzer:
  exclude: [build/**, android/**, ios/**, web/**, windows/**, macos/**, linux/**]
  language:
    strict-raw-types: true
linter:
  rules:
    constant_identifier_names: false