import 'package:badi_date/bahai_holyday.dart';

const MONTH_NAMES = {
  1: 'Bahá',
  2: 'Jalál',
  3: 'Jamál',
  4: '‘Aẓamat',
  5: 'Núr',
  6: 'Raḥmat',
  7: 'Kalimát',
  8: 'Kamál',
  9: 'Asmá’',
  10: '‘Izzat',
  11: 'Mashíyyat',
  12: '‘Ilm',
  13: 'Qudrat',
  14: 'Qawl',
  15: 'Masá’il',
  16: 'Sharaf',
  17: 'Sulṭán',
  18: 'Mulk',
  19: '‘Alá’'
};

const Map<String, Map<int, String>> MONTH_NAME_TRANSLATIONS = {
  'en': {
    1: 'Splendour',
    2: 'Glory',
    3: 'Beauty',
    4: 'Grandeur',
    5: 'Light',
    6: 'Mercy',
    7: 'Words',
    8: 'Perfection',
    9: 'Names',
    10: 'Might',
    11: 'Will',
    12: 'Knowledge',
    13: 'Power',
    14: 'Speech',
    15: 'Questions',
    16: 'Honour',
    17: 'Sovereignty',
    18: 'Dominion',
    19: 'Loftiness'
  },
  'de': {
    1: 'Herrlichkeit',
    2: 'Ruhm',
    3: 'Schönheit',
    4: 'Größe',
    5: 'Licht',
    6: 'Barmherzigkeit',
    7: 'Worte',
    8: 'Vollkommenheit',
    9: 'Namen',
    10: 'Macht',
    11: 'Wille',
    12: 'Wissen',
    13: 'Kraft',
    14: 'Sprache',
    15: 'Fragen',
    16: 'Ehre',
    17: 'Hoheit',
    18: 'Herrschaft',
    19: 'Erhabenheit'
  },
  'es': {
    1: 'Esplendor',
    2: 'Gloria',
    3: 'Belleza',
    4: 'Grandeza',
    5: 'Luz',
    6: 'Misericordia',
    7: 'Palabra',
    8: 'Perfección',
    9: 'Nombres',
    10: 'Fuerza',
    11: 'Voluntad',
    12: 'Conocimiento',
    13: 'Poder',
    14: 'Discurso',
    15: 'Preguntas',
    16: 'Honor',
    17: 'Soberanía',
    18: 'Dominio',
    19: 'Sublimidad'
  },
  'fa': {
    1: 'بهاء',
    2: 'جلال',
    3: 'جمال',
    4: 'عظمة',
    5: 'نور',
    6: 'رحمة',
    7: 'كلمات',
    8: 'كمال',
    9: 'اسماء',
    10: 'عزة',
    11: 'مشية',
    12: 'علم',
    13: 'قدرة',
    14: 'قول',
    15: 'مسائل',
    16: 'شرف',
    17: 'سلطان',
    18: 'ملك',
    19: 'علاء'
  },
  'fr': {
    1: 'Splendeur',
    2: 'Gloire',
    3: 'Beauté',
    4: 'Grandeur',
    5: 'Lumière',
    6: 'Miséricorde',
    7: 'Paroles',
    8: 'Perfection',
    9: 'Noms',
    10: 'Puissance',
    11: 'Volonté',
    12: 'Connaissance',
    13: 'Pouvoir',
    14: 'Discours',
    15: 'Questions',
    16: 'Honneur',
    17: 'Souveraineté',
    18: 'Empire',
    19: 'Élévation'
  },
  'tr': {
    1: 'Görkem',
    2: 'İhtişam',
    3: 'Güzellik',
    4: 'Heybet',
    5: 'Işık',
    6: 'Merhamet',
    7: 'Kelimeler',
    8: 'Mükemmellik',
    9: 'İsimler',
    10: 'Güç',
    11: 'İrade',
    12: 'İlim',
    13: 'Kudret',
    14: 'Söz',
    15: 'Sorular',
    16: 'Onur',
    17: 'İktidar',
    18: 'Saltannat',
    19: 'Yücelik'
  },
};

const WEEK_DAY = {
  1: 'Kamál',
  2: 'Fiḍál',
  3: '‘Idál',
  4: 'Istijlál',
  5: 'Istiqlál',
  6: 'Jalál',
  7: 'Jamál',
};

const Map<String, Map<int, String>> WEEK_DAY_TRANSLATION = {
  'en': {
    1: 'Perfection',
    2: 'Grace',
    3: 'Justice',
    4: 'Majesty',
    5: 'Independence',
    6: 'Glory',
    7: 'Beauty',
  },
  'de': {
    1: 'Vollkommenheit',
    2: 'Gnade',
    3: 'Gerechtigkeit',
    4: 'Majestät',
    5: 'Unabhängigkeit',
    6: 'Ruhm',
    7: 'Schönheit',
  },
  'es': {
    1: 'Perfección',
    2: 'Gracia',
    3: 'Justicia',
    4: 'Majestuocidad',
    5: 'Independencia',
    6: 'Gloria',
    7: 'Belleza',
  },
  'fa': {
    1: 'كمال',
    2: 'فضال',
    3: 'عدال',
    4: 'استجلال',
    5: 'استقلال',
    6: 'جلال',
    7: 'جمال',
  },
  'fr': {
    1: 'Perfection',
    2: 'Grâce',
    3: 'Justice',
    4: 'Majesté',
    5: 'Indépendance',
    6: 'Gloire',
    7: 'Beauté',
  },
  'tr': {
    1: 'Mükemmellik',
    2: 'Lütuf',
    3: 'Adalet',
    4: 'Haşmet',
    5: 'Bağımsızlık',
    6: 'İhtişam',
    7: 'Güzellik',
  },
};

const YEAR_NAMES = {
  1: 'Alif',
  2: 'Bá’',
  3: 'Ab',
  4: 'Dál',
  5: 'Báb',
  6: 'Váv',
  7: 'Abad',
  8: 'Jád',
  9: 'Bahá’',
  10: 'Ḥubb',
  11: 'Bahháj',
  12: 'Javáb',
  13: 'Aḥad',
  14: 'Vahháb',
  15: 'Vidád',
  16: 'Badí‘',
  17: 'Bahí',
  18: 'Abhá',
  19: 'Váḥid'
};

const Map<String, Map<int, String>> YEAR_NAME_TRANSLATIONS = {
  'en': {
    1: 'A',
    2: 'B',
    3: 'Father',
    4: 'D',
    5: 'Gate',
    6: 'V',
    7: 'Eternity',
    8: 'Generosity',
    9: 'Splendour',
    10: 'Love',
    11: 'Delightful',
    12: 'Answer',
    13: 'Single',
    14: 'Bountiful',
    15: 'Affection',
    16: 'Beginning',
    17: 'Luminous',
    18: 'Most Luminous',
    19: 'Unity'
  },
  'de': {
    1: 'A',
    2: 'B',
    3: 'Vater',
    4: 'D',
    5: 'Tor',
    6: 'V',
    7: 'Ewigkeit',
    8: 'Edelmut',
    9: 'Pracht',
    10: 'Liebe',
    11: 'Entzückend',
    12: 'Antwort',
    13: 'Einzig',
    14: 'Mildtätig',
    15: 'Zuneigung',
    16: 'Anfang',
    17: 'Strahlend',
    18: 'Überaus strahlend',
    19: 'Einheit'
  },
  'es': {
    1: 'A',
    2: 'B',
    3: 'Padre',
    4: 'D',
    5: 'Puerta',
    6: 'V',
    7: 'Eternidad',
    8: 'Generosidad',
    9: 'Esplendor',
    10: 'Amor',
    11: 'Encantador',
    12: 'Respuesta',
    13: 'Solo',
    14: 'Bondad',
    15: 'Afecto',
    16: 'Comienzo',
    17: 'Luminoso',
    18: 'Más Luminoso',
    19: 'Unidad'
  },
  'fa': {
    1: 'ألف',
    2: 'باء',
    3: 'أب',
    4: 'دﺍﻝ',
    5: 'باب',
    6: 'وﺍو',
    7: 'أبد',
    8: 'جاد',
    9: 'بهاء',
    10: 'حب',
    11: 'بهاج',
    12: 'جواب',
    13: 'احد',
    14: 'وﻫﺎب',
    15: 'وداد',
    16: 'بدیع',
    17: 'بهي',
    18: 'ابهى',
    19: 'واحد'
  },
  'fr': {
    1: 'A',
    2: 'B',
    3: 'Père',
    4: 'D',
    5: 'Porte',
    6: 'V',
    7: 'Éternité',
    8: 'Générosité',
    9: 'Splendeur',
    10: 'Amour',
    11: 'Délicieux',
    12: 'Réponse',
    13: 'Un(ique)',
    14: 'Libéral',
    15: 'Affection',
    16: 'Début',
    17: 'Splendide',
    18: 'Plus splendide',
    19: 'Unité'
  },
  'tr': {
    1: 'A',
    2: 'B',
    3: 'Baba',
    4: 'D',
    5: 'Kapı',
    6: 'V',
    7: 'Sonsuzluk',
    8: 'Cömertlik',
    9: 'Görkem',
    10: 'Sevgi',
    11: 'Güzel',
    12: 'Yanıt',
    13: 'Tek',
    14: 'Çok Bağışlayan',
    15: 'Muhabbet',
    16: 'Başlangıç',
    17: 'Aydınlık',
    18: 'En Parlak',
    19: 'Birlik'
  },
};

const Map<String, Map<BahaiHolyDayEnum, String>> HOLY_DAYS = {
  'en': {
    BahaiHolyDayEnum.NAW_RUZ: 'Naw-Rúz',
    BahaiHolyDayEnum.RIDVAN1ST: '1st day of Riḍván',
    BahaiHolyDayEnum.RIDVAN9TH: '9th day of Riḍván',
    BahaiHolyDayEnum.RIDVAN12TH: '12th day of Riḍván',
    BahaiHolyDayEnum.DECLARATION_OF_THE_BAB: 'Declaration of the Báb',
    BahaiHolyDayEnum.ASCENSION_OF_BAHAULLAH: 'Ascension of Bahá’u’lláh',
    BahaiHolyDayEnum.MARTYRDOM_OF_THE_BAB: 'Martyrdom of the Báb',
    BahaiHolyDayEnum.BIRTH_OF_THE_BAB: 'Birth of the Báb',
    BahaiHolyDayEnum.BIRTH_OF_BAHAULLAH: 'Birth of Bahá’u’lláh',
    BahaiHolyDayEnum.DAY_OF_THE_COVENANT: 'Day of the Covenant',
    BahaiHolyDayEnum.ASCENSION_OF_ABDUL_BAHA: 'Ascension of `Abdu’l-Bahá'
  },
  'fa': {
    BahaiHolyDayEnum.NAW_RUZ: 'نوروز',
    BahaiHolyDayEnum.RIDVAN1ST: 'اول رضوان',
    BahaiHolyDayEnum.RIDVAN9TH: 'نهم رضوان',
    BahaiHolyDayEnum.RIDVAN12TH: 'دوازدهم رضوان',
    BahaiHolyDayEnum.DECLARATION_OF_THE_BAB: 'اظهار امر حضرت باب',
    BahaiHolyDayEnum.ASCENSION_OF_BAHAULLAH: 'صعود حضرت بهاالله',
    BahaiHolyDayEnum.MARTYRDOM_OF_THE_BAB: 'شهادت حضرت باب',
    BahaiHolyDayEnum.BIRTH_OF_THE_BAB: 'تولد حضرت باب',
    BahaiHolyDayEnum.BIRTH_OF_BAHAULLAH: 'تولد حضرت بهاالله',
    BahaiHolyDayEnum.DAY_OF_THE_COVENANT: 'روز عهد',
    BahaiHolyDayEnum.ASCENSION_OF_ABDUL_BAHA: 'صعود حضرت عبدالبها'
  },
  'es': {
    BahaiHolyDayEnum.NAW_RUZ: 'Naw-Rúz',
    BahaiHolyDayEnum.RIDVAN1ST: 'Primer día de Riḍván',
    BahaiHolyDayEnum.RIDVAN9TH: 'Noveno día de Riḍván',
    BahaiHolyDayEnum.RIDVAN12TH: 'Duodécimo día de Riḍván',
    BahaiHolyDayEnum.DECLARATION_OF_THE_BAB: 'Declaración de Él Báb',
    BahaiHolyDayEnum.ASCENSION_OF_BAHAULLAH: 'Ascensión de Bahá’u’lláh',
    BahaiHolyDayEnum.MARTYRDOM_OF_THE_BAB: 'Martirio de Él Báb',
    BahaiHolyDayEnum.BIRTH_OF_THE_BAB: 'Nacimiento de Él Báb',
    BahaiHolyDayEnum.BIRTH_OF_BAHAULLAH: 'Nacimiento de Bahá’u’lláh',
    BahaiHolyDayEnum.DAY_OF_THE_COVENANT: 'Día del Convenio',
    BahaiHolyDayEnum.ASCENSION_OF_ABDUL_BAHA: 'Ascensión de `Abdu’l-Bahá'
  },
  'de': {
    BahaiHolyDayEnum.NAW_RUZ: 'Naw-Rúz',
    BahaiHolyDayEnum.RIDVAN1ST: '1. Riḍván',
    BahaiHolyDayEnum.RIDVAN9TH: '9. Riḍván',
    BahaiHolyDayEnum.RIDVAN12TH: '12. Riḍván',
    BahaiHolyDayEnum.DECLARATION_OF_THE_BAB: 'Erklärung des Báb',
    BahaiHolyDayEnum.ASCENSION_OF_BAHAULLAH: 'Hinscheiden Bahá’u’lláhs',
    BahaiHolyDayEnum.MARTYRDOM_OF_THE_BAB: 'Märtyertod des Báb',
    BahaiHolyDayEnum.BIRTH_OF_THE_BAB: 'Geburt des Báb',
    BahaiHolyDayEnum.BIRTH_OF_BAHAULLAH: 'Geburt Bahá’u’lláhs',
    BahaiHolyDayEnum.DAY_OF_THE_COVENANT: 'Tag des Bundes',
    BahaiHolyDayEnum.ASCENSION_OF_ABDUL_BAHA: 'Hinscheiden `Abdu’l-Bahás'
  },
  'fr': {
    BahaiHolyDayEnum.NAW_RUZ: 'Naw-Rúz',
    BahaiHolyDayEnum.RIDVAN1ST: 'Premier jour de Riḍvān',
    BahaiHolyDayEnum.RIDVAN9TH: 'Neuvième jour de Riḍvān',
    BahaiHolyDayEnum.RIDVAN12TH: 'Douzième jour de Riḍvān',
    BahaiHolyDayEnum.DECLARATION_OF_THE_BAB: 'Déclaration du Bāb',
    BahaiHolyDayEnum.ASCENSION_OF_BAHAULLAH: 'Ascension de Bahāʾ-Allāh',
    BahaiHolyDayEnum.MARTYRDOM_OF_THE_BAB: 'Martyre du Bāb',
    BahaiHolyDayEnum.BIRTH_OF_THE_BAB: 'Naissance du Bāb',
    BahaiHolyDayEnum.BIRTH_OF_BAHAULLAH: 'Naissance de Bahāʾ-Allāh',
    BahaiHolyDayEnum.DAY_OF_THE_COVENANT: 'Jour de l’Alliance',
    BahaiHolyDayEnum.ASCENSION_OF_ABDUL_BAHA: 'Ascension de ʿAbd-al-Bahāʾ'
  },
  'tr': {
    BahaiHolyDayEnum.NAW_RUZ: 'Naw-Rúz',
    BahaiHolyDayEnum.RIDVAN1ST: 'Rızvan’ın 1. günü',
    BahaiHolyDayEnum.RIDVAN9TH: 'Rızvan’ın 9. günü',
    BahaiHolyDayEnum.RIDVAN12TH: 'Rızvan’ın 12. günü',
    BahaiHolyDayEnum.DECLARATION_OF_THE_BAB: 'Hz. Bab’ın Emrini Açıklaması',
    BahaiHolyDayEnum.ASCENSION_OF_BAHAULLAH: 'Hz. Bahaullah’ın Suudu',
    BahaiHolyDayEnum.MARTYRDOM_OF_THE_BAB: 'Hz. Bab’ın Şehadeti',
    BahaiHolyDayEnum.BIRTH_OF_THE_BAB: 'Hz. Bab’ın Doğumu',
    BahaiHolyDayEnum.BIRTH_OF_BAHAULLAH: 'Hz. Bahaullah’ın Doğumu',
    BahaiHolyDayEnum.DAY_OF_THE_COVENANT: 'Misak Günü',
    BahaiHolyDayEnum.ASCENSION_OF_ABDUL_BAHA: 'Hz. Abdülbaha’nın Suudu'
  },
};

const LANGUAGES = {
  'en': 'English',
  'de': 'Deutsch',
  'es': 'Español',
  'fa': 'فارسی',
  'fr': 'Français',
  'tr': 'Türkçe',
};

const Map<String, Map<int, String>> WEEKDAYS_GREGORIAN = {
  'en': {
    1: 'Mon',
    2: 'Tue',
    3: 'Wed',
    4: 'Thu',
    5: 'Fri',
    6: 'Sat',
    7: 'Sun',
  },
  'de': {
    1: 'Mo.',
    2: 'Di.',
    3: 'Mi.',
    4: 'Do.',
    5: 'Fr.',
    6: 'Sa.',
    7: 'So.',
  },
  'es': {
    1: 'lun.',
    2: 'mar.',
    3: 'mié.',
    4: 'jue.',
    5: 'vie.',
    6: 'sáb.',
    7: 'dom.',
  },
  'fa': {
    1: 'دوشَنبه',
    2: 'سَهشَنبه',
    3: 'چِهار شَنبه',
    4: 'پَنج شَنبه',
    5: 'جُمعه',
    6: 'شَنبه',
    7: 'یَکشَنبه',
  },
  'fr': {
    1: 'lun',
    2: 'mar',
    3: 'mer',
    4: 'jeu',
    5: 'ven',
    6: 'sam',
    7: 'dim',
  },
  'tr': {
    1: 'Pzt',
    2: 'Sal',
    3: 'Çar',
    4: 'Per',
    5: 'Cum',
    6: 'Cmt',
    7: 'Paz',
  },
};
